version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    environment:
      - MSSQL_SA_PASSWORD=pakepwdsndiri
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
